version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: sudo composer self-update

      - run:
          name: Delete vendor
          command: rm -rf ./vendor

      # restore cache if `composer.lock` does not change
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # Run PHP Unit
      - run:
          name: Run PHP Unit
          command: ./vendor/bin/phpunit
