<?php

namespace Svea\Checkout\Tests\Unit\Validation\Admin;

use Svea\Checkout\Tests\Unit\TestCase;
use Svea\Checkout\Validation\Admin\ValidateGetDataFromLink;

class ValidateGetDataFromLinkTest extends TestCase
{

    private $validateUrl;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->validateUrl = new ValidateGetDataFromLink();
    }

    public function testValidateWithUrlAsString()
    {
        $url = 'SomeUrl';
        $this->validateUrl->validate($url);
    }

    /**
     * @expectedException \Svea\Checkout\Exception\SveaInputValidationException
     * @expectedExceptionCode Svea\Checkout\Exception\ExceptionCodeList::INPUT_VALIDATION_ERROR
     */
    public function testValidateWithEmptyUrl()
    {
        $url = '';
        $this->validateUrl->validate($url);
    }

    /**
     * @expectedException \Svea\Checkout\Exception\SveaInputValidationException
     * @expectedExceptionCode Svea\Checkout\Exception\ExceptionCodeList::INPUT_VALIDATION_ERROR
     */
    public function testValidateWithUrlAsInteger()
    {
        $url = 321;
        $this->validateUrl->validate($url);
    }

    /**
     * @expectedException \Svea\Checkout\Exception\SveaInputValidationException
     * @expectedExceptionCode Svea\Checkout\Exception\ExceptionCodeList::INPUT_VALIDATION_ERROR
     */
    public function testValidateWithUrlAsArray()
    {
        $url = array(1,2,3);
        $this->validateUrl->validate($url);
    }

    /**
     * @expectedException \Svea\Checkout\Exception\SveaInputValidationException
     * @expectedExceptionCode Svea\Checkout\Exception\ExceptionCodeList::INPUT_VALIDATION_ERROR
     */
    public function testValidateWithUrlAsNull()
    {
        $url = null;
        $this->validateUrl->validate($url);
    }
}
